name: Continuous integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 17.x]

    steps:
      # Retain Yarn cache across builds
      - name: Get Yarn cache path
        id: yarn-cache-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - name: Restore Yarn cache
        id: yarn-cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-path.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.node-version }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-yarn-

      # Retain Node modules across builds; Puppeteer is located inside here at
      # node_modules/puppeteer/.local-chromium
      - name: Restore Node modules cache
        uses: actions/cache@v2
        id: node-modules-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-node-modules-

      - name: Checkout source
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test

      - name: Lint
        run: yarn prettier --check .

      - name: Publish image snapshot diffs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: image-snapshots-diff-output
          path: |
            **/__image_snapshots__/__diff_output__/*
